### ISSUE TITLE
Update the Readme.md file with features and proper screenshots

### ISSUE THREAD

**Issue by Rohan-450** [Rohan-450/Digiconvert-Calculator#4] opened 2024-01-01 19:15 UTC
write about the project and the problem it solves, different techs used, use images or video for better representation

**Comment by AnitSarkar123** [comment] 2024-01-02 09:50
Assign me under Apertre'24

**Comment by Rohan-450** [comment] 2024-01-02 10:52
sure but will assign you but a bit later unless some changes will not be visible

**Comment by Sneha123-zudo** [comment] 2024-01-07 20:58
Please assign me this issue

**Comment by Sneha123-zudo** [comment] 2024-01-11 22:11
I'm interested in solving this issue, please assign me this issue

**Comment by abhraneel2004** [comment] 2024-01-15 18:29
Seems like the issue is still not solved yet. Can you assign It to me PA?

**Closed as completed** 2024-01-16 15:23 UTC
Labels: documentation, good first issue, apertre, easy
